spring.application.name=aggregator-api
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:threatdb}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:password123}

# Automatically creates the database tables based on Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Azure will provide ABUSEIPDB_API_KEY
abuseipdb.api.key=${ABUSEIPDB_API_KEY:8c808ede93e2d918d18a7a05aba8c6030e0ab8cefa9a60cd49d9705b6c36208740f03221c3644976}
