spring.application.name=aggregator-api
spring.datasource.url=jdbc:postgresql://localhost:5432/threatdb
spring.datasource.username=admin
spring.datasource.password=password123

# Automatically creates the database tables based on Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# External APIs
abuseipdb.api.key=8c808ede93e2d918d18a7a05aba8c6030e0ab8cefa9a60cd49d9705b6c36208740f03221c3644976