spring.application.name=aggregator-api
spring.datasource.url=jdbc:postgresql://localhost:5432/threatdb
spring.datasource.username=admin
spring.datasource.password=password123

# Automatically creates the database tables based on Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect